// Generated by CoffeeScript 1.8.0
var closeThisTab;

chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
  console.log('got message', request, sender);
  if (request.msg === 'acceptDanger') {
    chrome.downloads.acceptDangerAsync(request.downloadId).then(function() {
      if (chrome.runtime.lastError) {
        return console.log(chrome.runtime.lastError);
      } else {
        return console.log('no error');
      }
    });
  }
  if (request.msg === 'download') {
    $("#downloads").append("<li><a href='" + request.url + "' download='" + request.filename + "'>" + request.filename + "</a></li>");
    return chrome.downloads.download({
      filename: request.filename,
      url: request.url
    }, function(downloadId) {
      return chrome.downloads.acceptDanger(downloadId, function() {
        if (chrome.runtime.lastError) {
          return console.log('got error', chrome.runtime.lastError.message) && closeThisTab();
        } else {
          return closeThisTab();
        }
      });
    });
  }
});

closeThisTab = null;

//# sourceMappingURL=acceptDanger.js.map
